[theme]
base = "dark"
primaryColor = "#00c853"  # Bright Green for highlights & buttons
backgroundColor = "#0a0f0d"  # Very Dark Greenish Black for the main background
secondaryBackgroundColor = "#003d33"  # Deep Teal-Green for sidebar & panels
textColor = "#e0f2f1"  # Soft Cyan-White for readability
font = "sans serif"
